javascript: (function () {
    f0 = document.forms[0];
    f0['u_email0'].value = "minh";
    document.getElementById('u_email1').value = "gmail.com";
    document.getElementById('u_pwd').value = "123456789";
    document.getElementById('u_pwd_confirm').value = "123456789";
    f0['u_surname'].value = "Minh";
    f0['u_kname'].value ="MINHZ";
    f0['u_birth0'].value ="1998";
    f0['u_birth1'].value = "5";
    f0['u_birth2'].value = "9";
    f0['u_age'].value = "22";
    f0['u_nation'].value = "VNM";
    f0['u_job'].value = "1";
    f0['u_tel'].value = "123456789";
    f0['u_hp'].value = "987654321";
    f0['u_addr'].value = "Mo Dao, Que Vo, Bac Ninh";
    f0['u_motive'].value ="1";
    f0['u_purpose'].value ="1";
    f0['u_sid'].value = "111111111";
    document.getElementById('u_sex1').checked ="checked";
    document.getElementById('u_sex0').checked ="";
  })();